# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opc < Formula
  desc "CLI companion for platform engineers — persistent context, memory, and session management"
  homepage "https://github.com/opscompanion/opc"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/opscompanion/opc/releases/download/v0.7.0/opc_darwin_amd64.tar.gz"
      sha256 "f46bd45f2383ab12e68059493186338d156071574c3f03d3bfdfa3731ebc3776"

      define_method(:install) do
        bin.install "opc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/opscompanion/opc/releases/download/v0.7.0/opc_darwin_arm64.tar.gz"
      sha256 "a4ce9e5d5ae93ca0672fbf99f2dd375c9104da9b7da3ca9c63a75ce98945cb78"

      define_method(:install) do
        bin.install "opc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/opscompanion/opc/releases/download/v0.7.0/opc_linux_amd64.tar.gz"
      sha256 "c7589cad7ce0c01909bcfa87a84d8c6ee04bd143c7122390f047e85e64a82195"
      define_method(:install) do
        bin.install "opc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/opscompanion/opc/releases/download/v0.7.0/opc_linux_arm64.tar.gz"
      sha256 "fc729066a8b7c880ca2e4ce956f08b1c151e40d5228344a7d5dd52150c476232"
      define_method(:install) do
        bin.install "opc"
      end
    end
  end

  test do
    system "#{bin}/opc", "version"
  end
end
